# Generated by Django 3.1.3 on 2020-11-03 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('software_name', models.CharField(max_length=100)),
                ('license_key', models.CharField(max_length=100)),
                ('purchase_date', models.CharField(max_length=8)),
                ('renewal_date', models.CharField(blank=True, max_length=8)),
                ('license_assigned_to', models.CharField(max_length=50)),
            ],
        ),
    ]
