# Generated by Django 3.1.3 on 2020-11-03 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20201103_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_assigned_by',
            field=models.CharField(choices=[('andrew', 'Andrew')], default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
