# Generated by Django 3.1.3 on 2020-11-06 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_license_license_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_assigned_by',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='license',
            name='renewal_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
